// Полные данные для 7 языков: русский, китайский, арамейский, английский, греческий, славянский, церковный

export interface AlphabetLetter {
  letter: string
  name: string
  transcription: string
  example: string
  exampleTranslation: string
}

export interface Phrase {
  original: string
  transcription: string
  translation: string
}

export interface VocabItem {
  word: string
  transcription: string
  translation: string
  example?: string
}

export interface Lesson {
  id: string
  title: string
  level: 'Начальный' | 'Средний' | 'Продвинутый'
  description: string
  vocabulary: VocabItem[]
  grammarNote: string
}

export interface QuizQuestion {
  question: string
  options: string[]
  correct: number
  explanation: string
}

export interface CultureFact {
  title: string
  content: string
  emoji: string
}

export interface ReadingText {
  title: string
  text: string
  translation: string
  level: 'Начальный' | 'Средний' | 'Продвинутый'
  questions: {
    question: string
    options: string[]
    correct: number
    explanation: string
  }[]
}

export interface Language {
  id: string
  name: string
  nativeName: string
  tagline: string
  description: string
  longDescription: string
  family: string
  speakers: string
  script: string
  direction: 'ltr' | 'rtl'
  era: string
  color: string
  gradient: string
  accent: string
  emoji: string
  history: string[]
  alphabet: AlphabetLetter[]
  phrases: Phrase[]
  lessons: Lesson[]
  quiz: QuizQuestion[]
  culture: CultureFact[]
  proverbs: { original: string; translation: string; meaning: string }[]
  reading: ReadingText[]
}

export const languages: Language[] = [
  // ============ РУССКИЙ ============
  {
    id: 'russian',
    name: 'Русский',
    nativeName: 'Русский язык',
    tagline: 'Язык Пушкина, Достоевского и Толстого',
    description: 'Восточнославянский язык, один из самых распространённых в мире',
    longDescription: 'Русский язык — государственный язык Российской Федерации, один из шести официальных и рабочих языков ООН. Относится к восточнославянской подгруппе славянских языков индоевропейской семьи. На русском говорят около 260 миллионов человек по всему миру, и для approximately 150 миллионов он является родным. Богатая литературная традиция делает его одним из важнейших языков мировой культуры.',
    family: 'Индоевропейская, славянская ветвь',
    speakers: '~258 млн',
    script: 'Кириллица (33 буквы)',
    direction: 'ltr',
    era: 'Современный',
    color: 'rose',
    gradient: 'from-rose-500 to-orange-500',
    accent: 'bg-rose-500',
    emoji: '🇷🇺',
    history: [
      'VI век — формирование праславянского языка-основы',
      'IX век — создание Кириллом и Мефодием славянской азбуки (глаголицы, затем кириллицы)',
      'XVIII век — реформы Петра I, формирование современного литературного языка',
      '1918 год — орфографическая реформа, утверждение современного алфавита',
    ],
    alphabet: [
      { letter: 'А', name: 'а', transcription: 'a', example: 'Арбуз', exampleTranslation: 'Arbuz — арбуз' },
      { letter: 'Б', name: 'бэ', transcription: 'b', example: 'Банан', exampleTranslation: 'Banаn — банан' },
      { letter: 'В', name: 'вэ', transcription: 'v', example: 'Вода', exampleTranslation: 'Voda — вода' },
      { letter: 'Г', name: 'гэ', transcription: 'g', example: 'Город', exampleTranslation: 'Gorod — город' },
      { letter: 'Д', name: 'дэ', transcription: 'd', example: 'Дом', exampleTranslation: 'Dom — дом' },
      { letter: 'Е', name: 'е', transcription: 'ye', example: 'Ель', exampleTranslation: 'Yel — ель' },
      { letter: 'Ж', name: 'жэ', transcription: 'zh', example: 'Жук', exampleTranslation: 'Zhuk — жук' },
      { letter: 'З', name: 'зэ', transcription: 'z', example: 'Зима', exampleTranslation: 'Zima — зима' },
      { letter: 'И', name: 'и', transcription: 'i', example: 'Игра', exampleTranslation: 'Igra — игра' },
      { letter: 'Й', name: 'и краткое', transcription: 'y', example: 'Йогурт', exampleTranslation: 'Yogurt — йогурт' },
      { letter: 'К', name: 'ка', transcription: 'k', example: 'Кот', exampleTranslation: 'Kot — кот' },
      { letter: 'Л', name: 'эль', transcription: 'l', example: 'Лес', exampleTranslation: 'Les — лес' },
      { letter: 'М', name: 'эм', transcription: 'm', example: 'Море', exampleTranslation: 'More — море' },
      { letter: 'Н', name: 'эн', transcription: 'n', example: 'Нос', exampleTranslation: 'Nos — нос' },
      { letter: 'О', name: 'о', transcription: 'o', example: 'Облако', exampleTranslation: 'Oblako — облако' },
      { letter: 'П', name: 'пэ', transcription: 'p', example: 'Пирог', exampleTranslation: 'Pirog — пирог' },
      { letter: 'Р', name: 'эр', transcription: 'r', example: 'Река', exampleTranslation: 'Reka — река' },
      { letter: 'С', name: 'эс', transcription: 's', example: 'Солнце', exampleTranslation: 'Solntse — солнце' },
      { letter: 'Т', name: 'тэ', transcription: 't', example: 'Торт', exampleTranslation: 'Tort — торт' },
      { letter: 'У', name: 'у', transcription: 'u', example: 'Утка', exampleTranslation: 'Utka — утка' },
      { letter: 'Ф', name: 'эф', transcription: 'f', example: 'Флаг', exampleTranslation: 'Flag — флаг' },
      { letter: 'Х', name: 'ха', transcription: 'kh', example: 'Хлеб', exampleTranslation: 'Khleb — хлеб' },
      { letter: 'Ц', name: 'цэ', transcription: 'ts', example: 'Цветок', exampleTranslation: 'Tsvetok — цветок' },
      { letter: 'Ч', name: 'че', transcription: 'ch', example: 'Чай', exampleTranslation: 'Chay — чай' },
      { letter: 'Ш', name: 'ша', transcription: 'sh', example: 'Шар', exampleTranslation: 'Shar — шар' },
      { letter: 'Щ', name: 'ща', transcription: 'shch', example: 'Щука', exampleTranslation: 'Shchuka — щука' },
      { letter: 'Ъ', name: 'твёрдый знак', transcription: '—', example: 'Подъезд', exampleTranslation: 'Pod\'yezd — подъезд' },
      { letter: 'Ы', name: 'ы', transcription: 'y', example: 'Сыр', exampleTranslation: 'Syr — сыр' },
      { letter: 'Ь', name: 'мягкий знак', transcription: '—', example: 'Конь', exampleTranslation: 'Kon\' — конь' },
      { letter: 'Э', name: 'э', transcription: 'e', example: 'Этаж', exampleTranslation: 'Etazh — этаж' },
      { letter: 'Ю', name: 'ю', transcription: 'yu', example: 'Юбка', exampleTranslation: 'Yubka — юбка' },
      { letter: 'Я', name: 'я', transcription: 'ya', example: 'Яблоко', exampleTranslation: 'Yabloko — яблоко' },
    ],
    phrases: [
      { original: 'Привет!', transcription: 'Privet!', translation: 'Приветствие (неформальное)' },
      { original: 'Здравствуйте!', transcription: 'Zdravstvuyte!', translation: 'Здравствуйте (формально)' },
      { original: 'Как дела?', transcription: 'Kak dela?', translation: 'Как дела?' },
      { original: 'Спасибо большое', transcription: 'Spasibo bol\'shoye', translation: 'Большое спасибо' },
      { original: 'Пожалуйста', transcription: 'Pozhaluysta', translation: 'Пожалуйста / Не за что' },
      { original: 'Извините', transcription: 'Izvinite', translation: 'Извините' },
      { original: 'Я не понимаю', transcription: 'Ya ne ponimayu', translation: 'Я не понимаю' },
      { original: 'Вы говорите по-русски?', transcription: 'Vy govorite po-russki?', translation: 'Вы говорите по-русски?' },
      { original: 'Меня зовут...', transcription: 'Menya zovut...', translation: 'Меня зовут...' },
      { original: 'Очень приятно', transcription: 'Ochen\' priyatno', translation: 'Очень приятно' },
      { original: 'До свидания', transcription: 'Do svidaniya', translation: 'До свидания' },
      { original: 'Где находится...?', transcription: 'Gde nakhoditsya...?', translation: 'Где находится...?' },
    ],
    lessons: [
      {
        id: 'ru-1',
        title: 'Знакомство и приветствия',
        level: 'Начальный',
        description: 'Базовые формулы вежливости и представление себя',
        vocabulary: [
          { word: 'привет', transcription: 'privet', translation: 'привет' },
          { word: 'здравствуйте', transcription: 'zdravstvuyte', translation: 'здравствуйте' },
          { word: 'имя', transcription: 'imya', translation: 'имя' },
          { word: 'друг', transcription: 'drug', translation: 'друг' },
          { word: 'семья', transcription: 'sem\'ya', translation: 'семья' },
        ],
        grammarNote: 'В русском языке различают обращение на «ты» (неформальное) и на «Вы» (уважительное). Глаголы изменяются по лицам: я говорю, ты говоришь, он/она говорит, мы говорим, вы говорите, они говорят.',
      },
      {
        id: 'ru-2',
        title: 'Числа и счёт',
        level: 'Начальный',
        description: 'Учимся считать от 1 до 10',
        vocabulary: [
          { word: 'один', transcription: 'odin', translation: 'один' },
          { word: 'два', transcription: 'dva', translation: 'два' },
          { word: 'три', transcription: 'tri', translation: 'три' },
          { word: 'четыре', transcription: 'chetyre', translation: 'четыре' },
          { word: 'пять', transcription: 'pyat\'', translation: 'пять' },
          { word: 'шесть', transcription: 'shest\'', translation: 'шесть' },
          { word: 'семь', transcription: 'sem\'', translation: 'семь' },
          { word: 'восемь', transcription: 'vosem\'', translation: 'восемь' },
          { word: 'девять', transcription: 'devyat\'', translation: 'девять' },
          { word: 'десять', transcription: 'desyat\'', translation: 'десять' },
        ],
        grammarNote: 'Русские числительные имеют сложную систему склонения. Числительные 1, 21, 31 требуют именительного падежа существительного; 2-4, 22-24 — родительного единственного; 5-20, 25-30 — родительного множественного.',
      },
      {
        id: 'ru-3',
        title: 'Время и дни недели',
        level: 'Средний',
        description: 'Говорим о времени и расписании',
        vocabulary: [
          { word: 'понедельник', transcription: 'ponedelnik', translation: 'понедельник' },
          { word: 'вторник', transcription: 'vtornik', translation: 'вторник' },
          { word: 'среда', transcription: 'sreda', translation: 'среда' },
          { word: 'четверг', transcription: 'chetverg', translation: 'четверг' },
          { word: 'пятница', transcription: 'pyatnitsa', translation: 'пятница' },
          { word: 'суббота', transcription: 'subbota', translation: 'суббота' },
          { word: 'воскресенье', transcription: 'voskresene', translation: 'воскресенье' },
          { word: 'сегодня', transcription: 'segodnya', translation: 'сегодня' },
          { word: 'завтра', transcription: 'zavtra', translation: 'завтра' },
          { word: 'вчера', transcription: 'vchera', translation: 'вчера' },
        ],
        grammarNote: 'Дни недели в русском языке — существительные мужского (понедельник, вторник, четверг, пятница... ой, пятница женского) рода. После предлога «в» окончания меняются: во вторник, в среду, в четверг.',
      },
    ],
    quiz: [
      {
        question: 'Сколько букв в современном русском алфавите?',
        options: ['30', '31', '32', '33'],
        correct: 3,
        explanation: 'В русском алфавите 33 буквы — от А до Я.',
      },
      {
        question: 'Какая буква называется «и краткое»?',
        options: ['И', 'Й', 'Ы', 'Я'],
        correct: 1,
        explanation: 'Й — «и краткое», полугласный звук.',
      },
      {
        question: 'Выберите правильное написание:',
        options: ['подезд', 'подъезд', 'подъезд', 'подеэзд'],
        correct: 1,
        explanation: 'Разделительный твёрдый знак пишется после приставок на согласный перед е, ё, ю, я.',
      },
      {
        question: 'Какое слово означает «спасибо»?',
        options: ['пожалуйста', 'спасибо', 'извините', 'привет'],
        correct: 1,
        explanation: 'Спасибо — благодарность, от «спаси Бог».',
      },
      {
        question: 'Сколько падежей в русском языке?',
        options: ['4', '5', '6', '7'],
        correct: 2,
        explanation: 'В русском языке 6 падежей: именительный, родительный, дательный, винительный, творительный, предложный.',
      },
    ],
    culture: [
      { emoji: '📚', title: 'Золотой век литературы', content: 'XIX век дал миру Пушкина, Лермонтова, Гоголя, Толстого, Достоевского, Чехова. Русская литература стала одной из самых влиятельных в мире, оказав воздействие на развитие романа, рассказа и драматургии.' },
      { emoji: '🎭', title: 'Русский балет', content: 'Большой и Мариинский театры — символы русской культуры. Балет «Лебединое озеро» Чайковского исполняется по всему миру с 1877 года.' },
      { emoji: '🚀', title: 'Язык космоса', content: 'Русский — один из рабочих языков Международной космической станции (МКС). Астронавты обязаны знать русский для работы на российском сегменте.' },
      { emoji: '❄️', title: 'Богатство синонимов', content: 'В русском языке более 50 синонимов для слова «идти» (шагать, плестись, брести, ковылять, маршировать...) и десятки — для слова «хороший».' },
    ],
    proverbs: [
      { original: 'Семь раз отмерь, один раз отрежь', translation: 'Seven times measure, once cut', meaning: 'Семь раз подумай, прежде чем действовать' },
      { original: 'Тише едешь — дальше будешь', translation: 'Slower you go, further you get', meaning: 'Спешка вредит качеству' },
      { original: 'Без труда не выловишь и рыбку из пруда', translation: 'No pain, no gain', meaning: 'Без усилий нет результата' },
      { original: 'Что посеешь, то и пожнёшь', translation: 'You reap what you sow', meaning: 'Поступки имеют последствия' },
    ],
    reading: [
      {
        title: 'Мой день',
        level: 'Начальный',
        text: 'Меня зовут Анна. Я живу в Москве. Каждый день я встаю в семь утра. Я пью кофе и ем хлеб. Потом я иду на работу. Я работаю в школе. Я учитель. Вечером я читаю книги и смотрю телевизор. Я люблю мой день.',
        translation: 'My name is Anna. I live in Moscow. Every day I wake up at seven in the morning. I drink coffee and eat bread. Then I go to work. I work at a school. I am a teacher. In the evening I read books and watch TV. I love my day.',
        questions: [
          { question: 'Где живёт Анна?', options: ['В Петербурге', 'В Москве', 'В Киеве', 'В Сочи'], correct: 1, explanation: 'В тексте: «Я живу в Москве»' },
          { question: 'Во сколько она встаёт?', options: ['В 6 утра', 'В 7 утра', 'В 8 утра', 'В 9 утра'], correct: 1, explanation: 'В тексте: «Я встаю в семь утра»' },
          { question: 'Кем работает Анна?', options: ['Врачом', 'Учителем', 'Инженером', 'Поваром'], correct: 1, explanation: 'В тексте: «Я учитель»' },
        ],
      },
      {
        title: 'Русская зима',
        level: 'Средний',
        text: 'Русская зима — это особенное время года. В декабре выпадает снег, и земля становится белой. Люди катаются на лыжах, санках и коньках. Дети лепят снеговиков во дворах. Самый любимый праздник — Новый год. Люди наряжают ёлку, готовят вкусную еду и дарят друг другу подарки. В январе бывают сильные морозы, но русские люди привыкли к холоду.',
        translation: 'Russian winter is a special time of year. In December snow falls and the earth becomes white. People ski, sled, and skate. Children build snowmen in yards. The most beloved holiday is New Year. People decorate the Christmas tree, cook delicious food, and give each other gifts. In January there are severe frosts, but Russian people are used to the cold.',
        questions: [
          { question: 'Что происходит в декабре?', options: ['Тает снег', 'Выпадает снег', 'Цветут цветы', 'Жара'], correct: 1, explanation: 'В тексте: «В декабре выпадает снег»' },
          { question: 'Какой самый любимый праздник?', options: ['День Победы', 'Масленица', 'Новый год', 'Пасха'], correct: 2, explanation: 'В тексте: «Самый любимый праздник — Новый год»' },
          { question: 'Что лепят дети?', options: ['Замок', 'Снеговиков', 'Пироги', 'Город'], correct: 1, explanation: 'В тексте: «Дети лепят снеговиков»' },
        ],
      },
    ],
  },

  // ============ КИТАЙСКИЙ ============
  {
    id: 'chinese',
    name: 'Китайский',
    nativeName: '中文 / 汉语',
    tagline: 'Язык Поднебесной с 5000-летней историей',
    description: 'Самый распространённый родной язык в мире',
    longDescription: 'Китайский язык — язык сино-тибетской языковой семьи, на котором говорят более 1,3 миллиарда человек. Это самый распространённый родной язык в мире. Китайская письменность — одна из древнейших непрерывно используемых систем письма, насчитывающая более 3000 лет. Использует иероглифы (汉字), каждый из которых представляет слог и морфему. Современный нормативный китайский (путунхуа) основан на пекинском диалекте северной группы мандаринских диалектов.',
    family: 'Сино-тибетская',
    speakers: '~1,3 млрд',
    script: 'Иероглифы (汉字) + пиньинь',
    direction: 'ltr',
    era: 'Современный (путунхуа)',
    color: 'red',
    gradient: 'from-red-600 to-amber-500',
    accent: 'bg-red-600',
    emoji: '🇨🇳',
    history: [
      'Около 1250 г. до н.э. — древнейшие надписи на гадательных костях (цзягувэнь)',
      'III век до н.э. — Цинь Шихуанди унифицирует письменность',
      '1950-е годы — реформа и упрощение иероглифов в КНР',
      '1958 год — введение системы пиньинь для транскрипции',
    ],
    alphabet: [
      { letter: '你', name: 'nǐ', transcription: 'ni3', example: '你好', exampleTranslation: 'nǐ hǎo — привет' },
      { letter: '好', name: 'hǎo', transcription: 'hao3', example: '你好', exampleTranslation: 'nǐ hǎo — привет' },
      { letter: '我', name: 'wǒ', transcription: 'wo3', example: '我们', exampleTranslation: 'wǒ men — мы' },
      { letter: '是', name: 'shì', transcription: 'shi4', example: '是的', exampleTranslation: 'shì de — да' },
      { letter: '不', name: 'bù', transcription: 'bu4', example: '不是', exampleTranslation: 'bú shì — нет' },
      { letter: '人', name: 'rén', transcription: 'ren2', example: '中国人', exampleTranslation: 'Zhōngguó rén — китаец' },
      { letter: '大', name: 'dà', transcription: 'da4', example: '大学', exampleTranslation: 'dàxué — университет' },
      { letter: '小', name: 'xiǎo', transcription: 'xiao3', example: '小时', exampleTranslation: 'xiǎoshí — час' },
      { letter: '中', name: 'zhōng', transcription: 'zhong1', example: '中国', exampleTranslation: 'Zhōngguó — Китай' },
      { letter: '国', name: 'guó', transcription: 'guo2', example: '中国', exampleTranslation: 'Zhōngguó — Китай' },
      { letter: '日', name: 'rì', transcription: 'ri4', example: '日本', exampleTranslation: 'Rìběn — Япония' },
      { letter: '月', name: 'yuè', transcription: 'yue4', example: '月亮', exampleTranslation: 'yuèliang — луна' },
      { letter: '水', name: 'shuǐ', transcription: 'shui3', example: '喝水', exampleTranslation: 'hē shuǐ — пить воду' },
      { letter: '火', name: 'huǒ', transcription: 'huo3', example: '火车', exampleTranslation: 'huǒchē — поезд' },
      { letter: '山', name: 'shān', transcription: 'shan1', example: '高山', exampleTranslation: 'gāo shān — высокая гора' },
      { letter: '木', name: 'mù', transcription: 'mu4', example: '树木', exampleTranslation: 'shùmù — деревья' },
      { letter: '天', name: 'tiān', transcription: 'tian1', example: '天空', exampleTranslation: 'tiānkōng — небо' },
      { letter: '地', name: 'dì', transcription: 'di4', example: '地球', exampleTranslation: 'dìqiú — Земля' },
      { letter: '一', name: 'yī', transcription: 'yi1', example: '一个', exampleTranslation: 'yí gè — один (штука)' },
      { letter: '二', name: 'èr', transcription: 'er4', example: '二十', exampleTranslation: 'èrshí — двадцать' },
      { letter: '三', name: 'sān', transcription: 'san1', example: '三个', exampleTranslation: 'sān gè — три' },
      { letter: '四', name: 'sì', transcription: 'si4', example: '四十', exampleTranslation: 'sìshí — сорок' },
      { letter: '五', name: 'wǔ', transcription: 'wu3', example: '五个人', exampleTranslation: 'wǔ gè rén — пять человек' },
      { letter: '六', name: 'liù', transcription: 'liu4', example: '六本书', exampleTranslation: 'liù běn shū — шесть книг' },
      { letter: '七', name: 'qī', transcription: 'qi1', example: '七天', exampleTranslation: 'qī tiān — семь дней' },
      { letter: '八', name: 'bā', transcription: 'ba1', example: '八月', exampleTranslation: 'bā yuè — август' },
      { letter: '九', name: 'jiǔ', transcription: 'jiu3', example: '九月', exampleTranslation: 'jiǔ yuè — сентябрь' },
      { letter: '十', name: 'shí', transcription: 'shi2', example: '十个', exampleTranslation: 'shí gè — десять' },
      { letter: '口', name: 'kǒu', transcription: 'kou3', example: '人口', exampleTranslation: 'rénkǒu — население' },
      { letter: '心', name: 'xīn', transcription: 'xin1', example: '开心', exampleTranslation: 'kāixīn — счастливый' },
    ],
    phrases: [
      { original: '你好', transcription: 'nǐ hǎo', translation: 'Привет / Здравствуйте' },
      { original: '再见', transcription: 'zài jiàn', translation: 'До свидания' },
      { original: '谢谢', transcription: 'xiè xie', translation: 'Спасибо' },
      { original: '不客气', transcription: 'bú kè qi', translation: 'Не за что' },
      { original: '对不起', transcription: 'duì bu qǐ', translation: 'Извините' },
      { original: '没关系', transcription: 'méi guān xi', translation: 'Ничего страшного' },
      { original: '我叫...', transcription: 'wǒ jiào...', translation: 'Меня зовут...' },
      { original: '我听不懂', transcription: 'wǒ tīng bù dǒng', translation: 'Я не понимаю' },
      { original: '请说慢一点', transcription: 'qǐng shuō màn yì diǎn', translation: 'Говорите помедленнее' },
      { original: '多少钱?', transcription: 'duō shao qián?', translation: 'Сколько стоит?' },
      { original: '在哪里?', transcription: 'zài nǎ lǐ?', translation: 'Где это?' },
      { original: '我爱你', transcription: 'wǒ ài nǐ', translation: 'Я тебя люблю' },
    ],
    lessons: [
      {
        id: 'zh-1',
        title: 'Основы путунхуа',
        level: 'Начальный',
        description: 'Тоны и базовая грамматика',
        vocabulary: [
          { word: '你好', transcription: 'nǐ hǎo', translation: 'привет' },
          { word: '谢谢', transcription: 'xiè xie', translation: 'спасибо' },
          { word: '再见', transcription: 'zài jiàn', translation: 'до свидания' },
          { word: '请', transcription: 'qǐng', translation: 'пожалуйста' },
          { word: '对', transcription: 'duì', translation: 'правильно' },
        ],
        grammarNote: 'В китайском 4 тона: 1 (ровный —), 2 (восходящий /), 3 (нисходяще-восходящий ∨), 4 (нисходящий \\). Тон меняет значение слова: mā (мама) — mǎ (лошадь). Порядок слов: SVO (подлежащее — сказуемое — дополнение).',
      },
      {
        id: 'zh-2',
        title: 'Числа и счётные слова',
        level: 'Начальный',
        description: 'Счётные слова — основа китайского',
        vocabulary: [
          { word: '一', transcription: 'yī', translation: 'один' },
          { word: '二', transcription: 'èr', translation: 'два' },
          { word: '三', transcription: 'sān', translation: 'три' },
          { word: '十', transcription: 'shí', translation: 'десять' },
          { word: '百', transcription: 'bǎi', translation: 'сто' },
          { word: '个', transcription: 'gè', translation: 'счётное слово (общее)' },
          { word: '本', transcription: 'běn', translation: 'счётное слово для книг' },
          { word: '人', transcription: 'rén', translation: 'человек (счётное слово)' },
        ],
        grammarNote: 'Между числом и существительным обязательно ставится счётное слово: 一个人 (yí gè rén — один человек), 两本书 (liǎng běn shū — две книги). У разных существительных разные счётные слова.',
      },
      {
        id: 'zh-3',
        title: 'Семья и родственники',
        level: 'Средний',
        description: 'Сложная терминология родства',
        vocabulary: [
          { word: '爸爸', transcription: 'bà ba', translation: 'папа' },
          { word: '妈妈', transcription: 'mā ma', translation: 'мама' },
          { word: '哥哥', transcription: 'gē ge', translation: 'старший брат' },
          { word: '弟弟', transcription: 'dì di', translation: 'младший брат' },
          { word: '姐姐', transcription: 'jiě jie', translation: 'старшая сестра' },
          { word: '妹妹', transcription: 'mèi mei', translation: 'младшая сестра' },
          { word: '爷爷', transcription: 'yé ye', translation: 'дедушка (по отцу)' },
          { word: '奶奶', transcription: 'nǎi nai', translation: 'бабушка (по отцу)' },
        ],
        grammarNote: 'Китайская терминология родства очень точная: разные слова для старших/младших братьев и сестёр, а также для родственников со стороны отца и матери.',
      },
    ],
    quiz: [
      {
        question: 'Сколько тонов в путунхуа?',
        options: ['2', '3', '4', '5'],
        correct: 2,
        explanation: 'В путунхуа 4 основных тона + нейтральный (轻声).',
      },
      {
        question: 'Что означает «你好»?',
        options: ['Спасибо', 'Привет', 'До свидания', 'Извините'],
        correct: 1,
        explanation: '你好 (nǐ hǎo) — стандартное приветствие.',
      },
      {
        question: 'Какое число означает иероглиф 三?',
        options: ['1', '2', '3', '4'],
        correct: 2,
        explanation: '三 (sān) — три. Три горизонтальные черты.',
      },
      {
        question: 'Как читается «谢谢» в пиньине?',
        options: ['xiè xie', 'zài jiàn', 'nǐ hǎo', 'duì bu qǐ'],
        correct: 0,
        explanation: '谢谢 читается как xiè xie — спасибо.',
      },
      {
        question: 'Что обязательно между числом и существительным?',
        options: ['Глагол', 'Прилагательное', 'Счётное слово', 'Частица 了'],
        correct: 2,
        explanation: 'В китайском обязательно счётное слово (量词): 一个人, 两本书.',
      },
    ],
    culture: [
      { emoji: '🏮', title: 'Четыреечатый год', content: 'В Китае цифра 4 (四 sì) звучит как «смерть» (死 sǐ) — это табу. В зданиях часто нет 4-го этажа. Зато 8 (八 bā) созвучно с «разбогатеть» (发 fā) — это счастливое число.' },
      { emoji: '🐉', title: 'Иероглифы как искусство', content: 'Каллиграфия (书法 shūfǎ) — одно из высших искусств Китая. Каждый штрих имеет значение, порядок черт строго регламентирован. Великим каллиграфом был Ван Сичжи (303–361 н.э.).' },
      { emoji: '🎋', title: 'Чэнъюи — идиомы', content: 'Чэнъюи (成语) — четырёхсимвольные идиомы, восходящие к классической литературе. В китайском более 20 000 чэнъюев. Например, 画蛇添足 (huà shé tiān zú) — «рисовать змее ноги» (делать лишнее).' },
      { emoji: '🌏', title: 'Диалекты Китая', content: 'Китайский — макроязык из 7 основных диалектных групп. Путунхуа и кантонский носители не понимают друг друга. Но письменность едина для всех — иероглифы читаются по-разному, но смысл одинаков.' },
    ],
    proverbs: [
      { original: '千里之行，始于足下', translation: 'Qiān lǐ zhī xíng, shǐ yú zú xià', meaning: 'Путешествие в 1000 ли начинается с одного шага' },
      { original: '学而时习之', translation: 'Xué ér shí xí zhī', meaning: 'Учиться и регулярно повторять — путь к мудрости (Конфуций)' },
      { original: '不入虎穴，焉得虎子', translation: 'Bù rù hǔ xué, yān dé hǔ zǐ', meaning: 'Не войдя в логово тигра, не поймать тигрёнка (риск — благородное дело)' },
      { original: '授人以鱼不如授人以渔', translation: 'Shòu rén yǐ yú bùrú shòu rén yǐ yú', meaning: 'Лучше научить ловить рыбу, чем дать рыбу' },
    ],
    reading: [],
  },

  // ============ АРАМЕЙСКИЙ ============
  {
    id: 'aramaic',
    name: 'Арамейский',
    nativeName: 'ܐܪܡܝܐ / ארמית',
    tagline: 'Язык Иисуса и древних империй',
    description: 'Древний семитский язык Ближнего Востока',
    longDescription: 'Арамейский язык — древний семитский язык, на котором говорили в Месопотамии и Сирии более 3000 лет. Был lingua franca Ближнего Востока во времена Новоассирийской, Нововавилонской и Ахеменидской империй. На арамейском говорили Иисус Христос и его апостолы. Сегодня сохранились несколько современных арамейских диалектов (сиро-арамейский, туройо), на которых говорят небольшие общины в Сирии, Ираке, Турции и диаспоре. Письменность — арамейский алфавит, основа для еврейского, арабского и сирийского письма.',
    family: 'Афразийская, семитская ветвь',
    speakers: '~1 млн (современные диалекты)',
    script: 'Арамейский/сирийский алфавит (ܐܠܦܒܝܬ)',
    direction: 'rtl',
    era: 'Древний (с X в. до н.э.)',
    color: 'amber',
    gradient: 'from-amber-600 to-yellow-700',
    accent: 'bg-amber-600',
    emoji: '📜',
    history: [
      'XI век до н.э. — первые арамейские надписи',
      'VIII–VI века до н.э. — lingua franca Ассирии и Вавилонии',
      'V век до н.э. — официальный язык Персидской империи Ахеменидов',
      'I век н.э. — язык Иисуса и ранних христиан',
      'V–XIII века н.э. — золотой век сирийской христианской литературы',
    ],
    alphabet: [
      { letter: 'ܐ', name: 'Алаф', transcription: 'ā/’', example: 'ܐܒܐ', exampleTranslation: 'abā — отец' },
      { letter: 'ܒ', name: 'Бет', transcription: 'b/v', example: 'ܒܝܬ', exampleTranslation: 'baytā — дом' },
      { letter: 'ܓ', name: 'Гамал', transcription: 'g', example: 'ܓܡܠܐ', exampleTranslation: 'gamlā — верблюд' },
      { letter: 'ܕ', name: 'Далат', transcription: 'd', example: 'ܕܪܐ', exampleTranslation: 'darrā — поколение' },
      { letter: 'ܗ', name: 'Э', transcription: 'h', example: 'ܗܘ', exampleTranslation: 'hū — он' },
      { letter: 'ܘ', name: 'Вав', transcription: 'w/o/u', example: 'ܘܪܕܐ', exampleTranslation: 'wardā — роза' },
      { letter: 'ܙ', name: 'Зайн', transcription: 'z', example: 'ܙܗܪܐ', exampleTranslation: 'zahrā — цветок' },
      { letter: 'ܚ', name: 'Хет', transcription: 'ḥ', example: 'ܚܟܡܐ', exampleTranslation: 'ḥakkāmā — мудрец' },
      { letter: 'ܛ', name: 'Тет', transcription: 'ṭ', example: 'ܛܒ', exampleTranslation: 'ṭāb — хороший' },
      { letter: 'ܝ', name: 'Йуд', transcription: 'y/i', example: 'ܝܕܥ', exampleTranslation: 'yadaʿ — знать' },
      { letter: 'ܟ', name: 'Каф', transcription: 'k/kh', example: 'ܟܠ', exampleTranslation: 'kull — все' },
      { letter: 'ܠ', name: 'Ламад', transcription: 'l', example: 'ܠܒܐ', exampleTranslation: 'lebbā — сердце' },
      { letter: 'ܡ', name: 'Мим', transcription: 'm', example: 'ܡܠܟܐ', exampleTranslation: 'malkā — царь' },
      { letter: 'ܢ', name: 'Нун', transcription: 'n', example: 'ܢܘܢ', exampleTranslation: 'nūn — рыба' },
      { letter: 'ܣ', name: 'Семкат', transcription: 's', example: 'ܣܦܪܐ', exampleTranslation: 'seprā — книга' },
      { letter: 'ܥ', name: 'Эй', transcription: 'ʿ', example: 'ܥܝܢܐ', exampleTranslation: 'ʿaynā — глаз' },
      { letter: 'ܦ', name: 'Пэ', transcription: 'p/f', example: 'ܦܘܡܐ', exampleTranslation: 'pummā — рот' },
      { letter: 'ܨ', name: 'Цадэ', transcription: 'ṣ', example: 'ܨܕܝܕܐ', exampleTranslation: 'ṣadyādā — охотник' },
      { letter: 'ܩ', name: 'Коф', transcription: 'q', example: 'ܩܕܝܫܐ', exampleTranslation: 'qaddīšā — святой' },
      { letter: 'ܪ', name: 'Риш', transcription: 'r', example: 'ܪܝܫܐ', exampleTranslation: 'rīšā — голова' },
      { letter: 'ܫ', name: 'Шин', transcription: 'š', example: 'ܫܡܫܐ', exampleTranslation: 'šemšā — солнце' },
      { letter: 'ܬ', name: 'Тав', transcription: 't', example: 'ܬܘܪܐ', exampleTranslation: 'tawrā — бык' },
    ],
    phrases: [
      { original: 'ܫܠܡܐ ܥܠܝܟ', transcription: 'šlāmā ʿlayk', translation: 'Мир тебе / Привет' },
      { original: 'ܒܫܠܡܐ', transcription: 'b-šlāmā', translation: 'С миром / До свидания' },
      { original: 'ܬܘܒܝ', transcription: 'tawbay', translation: 'Спасибо' },
      { original: 'ܣܓܝ', transcription: 'saggī', translation: 'Много / Очень' },
      { original: 'ܠܐ ܡܫܬܡܥ', transcription: 'lā mšatmaʿ', translation: 'Я не понимаю' },
      { original: 'ܡܢܐ ܫܡܟ', transcription: 'mānā šmāk?', translation: 'Как тебя зовут?' },
      { original: 'ܫܡܝ', transcription: 'šmī', translation: 'Меня зовут...' },
      { original: 'ܐܝܟ ܚܙܝ', transcription: 'aykā ḥzay?', translation: 'Где это?' },
      { original: 'ܟܐ ܐܟܠ', transcription: 'kā akhal', translation: 'Я ем' },
      { original: 'ܟܐ ܫܬܐ', transcription: 'kā šātē', translation: 'Я пью' },
      { original: 'ܛܒ', transcription: 'ṭāb', translation: 'Хорошо' },
      { original: 'ܒܫܝܪܐ', transcription: 'b-šayrā', translation: 'С радостью' },
    ],
    lessons: [
      {
        id: 'ar-1',
        title: 'Основы арамейского письма',
        level: 'Начальный',
        description: 'Знакомство с эстрангело и сирта',
        vocabulary: [
          { word: 'ܐܒܐ', transcription: 'abā', translation: 'отец' },
          { word: 'ܐܡܐ', transcription: 'emmā', translation: 'мать' },
          { word: 'ܒܪܐ', transcription: 'barā', translation: 'сын' },
          { word: 'ܒܪܬܐ', transcription: 'bartā', translation: 'дочь' },
          { word: 'ܒܝܬܐ', transcription: 'baytā', translation: 'дом' },
        ],
        grammarNote: 'Арамейский — семитский язык с корневой системой. Большинство корней состоят из 3 согласных. Определённый артикль — суффикс -ā: malk (царь) → malkā (царь, известный). Письмо пишется справа налево.',
      },
      {
        id: 'ar-2',
        title: 'Библейские выражения',
        level: 'Средний',
        description: 'Фразы из Пешитты и Талмуда',
        vocabulary: [
          { word: 'ܐܠܗܐ', transcription: 'alāhā', translation: 'Бог' },
          { word: 'ܫܡܝܐ', transcription: 'šmayyā', translation: 'небо' },
          { word: 'ܐܪܥܐ', transcription: 'arʿā', translation: 'земля' },
          { word: 'ܪܘܚܐ', transcription: 'ruḥā', translation: 'дух' },
          { word: 'ܚܝܐ', transcription: 'ḥayyē', translation: 'жизнь' },
          { word: 'ܢܘܗܪܐ', transcription: 'nuhrā', translation: 'свет' },
          { word: 'ܫܠܡܐ', transcription: 'šlāmā', translation: 'мир' },
          { word: 'ܡܠܟܘܬܐ', transcription: 'malkūtā', translation: 'царство' },
        ],
        grammarNote: 'В классическом сирийском 2 состояния: абсолютное и сопряжённое. Сопряжённое используется при конструкции «сопряжённого possessivum»: baytā d-malkā (дом царя). Частица d- — связка «из, от, относящийся к».',
      },
      {
        id: 'ar-3',
        title: 'Числа в арамейском',
        level: 'Продвинутый',
        description: 'Кардинальные числа 1-10',
        vocabulary: [
          { word: 'ܚܕ', transcription: 'ḥad', translation: 'один' },
          { word: 'ܬܪܝܢ', transcription: 'trēn', translation: 'два' },
          { word: 'ܬܠܬܐ', transcription: 'tlātā', translation: 'три' },
          { word: 'ܐܪܒܥܐ', transcription: 'arbaʿā', translation: 'четыре' },
          { word: 'ܚܡܫܐ', transcription: 'ḥammšā', translation: 'пять' },
          { word: 'ܫܬܐ', transcription: 'šattā', translation: 'шесть' },
          { word: 'ܫܒܥܐ', transcription: 'šabʿā', translation: 'семь' },
          { word: 'ܬܡܢܝܐ', transcription: 'tmānyā', translation: 'восемь' },
          { word: 'ܬܫܥܐ', transcription: 'tishʿā', translation: 'девять' },
          { word: 'ܥܣܪܐ', transcription: 'ʿasrā', translation: 'десять' },
        ],
        grammarNote: 'Арамейские числа 3-10 имеют женский род с окончанием -ā и мужской без окончания. Это «обратное согласование»: masculine numbers take feminine nouns and vice versa — типичная семитская черта.',
      },
    ],
    quiz: [
      {
        question: 'В каком направлении пишется арамейский?',
        options: ['Слева направо', 'Сверху вниз', 'Справа налево', 'Снизу вверх'],
        correct: 2,
        explanation: 'Арамейский пишется справа налево, как иврит и арабский.',
      },
      {
        question: 'Кто говорил на арамейском в I веке н.э.?',
        options: ['Конфуций', 'Иисус Христос', 'Будда', 'Магомет'],
        correct: 1,
        explanation: 'Иисус и его апостолы говорили на арамейском языке.',
      },
      {
        question: 'Что означает ܐܒܐ (abā)?',
        options: ['мать', 'отец', 'брат', 'сын'],
        correct: 1,
        explanation: 'ܐܒܐ (abā) — отец. Ср. с авва в евангелиях.',
      },
      {
        question: 'Какая буква арамейского алфавита первая?',
        options: ['ܒ', 'ܐ', 'ܓ', 'ܕ'],
        correct: 1,
        explanation: 'ܐ (Алаф) — первая буква арамейского алфавита.',
      },
      {
        question: 'К какому языковому семейству относится арамейский?',
        options: ['Индоевропейская', 'Сино-тибетская', 'Афразийская (семитская)', 'Уральская'],
        correct: 2,
        explanation: 'Арамейский — семитский язык афразийской макросемьи.',
      },
    ],
    culture: [
      { emoji: '✝️', title: 'Язык Иисуса', content: 'В I веке н.э. Иисус и его апостолы говорили на арамейском. Знаменитые слова «Талифа куми» («Девица, встань»), «Элои, Элои, ламма савахфани?» («Боже мой, зачем ты меня оставил?») — арамейские.' },
      { emoji: '🏛️', title: 'Lingua franca древности', content: 'С VIII века до н.э. по IV век н.э. арамейский был lingua franca Ближнего Востока. На нём говорили от Египта до Индии, он был официальным языком Персидской империи Ахеменидов.' },
      { emoji: '📖', title: 'Пешитта', content: 'Пешитта («простая») — стандартная сирийская Библия, переведённая с еврейского на сирийский арамейский в V веке. До сих пор используется Сирийской православной церковью.' },
      { emoji: '🌍', title: 'Современные носители', content: 'Сегодня на новоарамейских диалектах говорят около 1 миллиона человек: ассирийцы и халдеи в Ираке, Сирии, Турции, Иране и в диаспоре. Язык под угрозой исчезновения.' },
    ],
    proverbs: [
      { original: 'ܡܠܬܐ ܕܦܬܓܡܐ ܫܦܝܪܬܐ', translation: 'miltā d-patgmā šapirtā', meaning: 'Слово во время — прекрасная жемчужина' },
      { original: 'ܟܠ ܕܙܪܥ ܙܪܥܐ ܕܚܛܗܐ ܚܨܕ ܚܛܗܐ', translation: 'kol d-zarʿ zarʿā d-ḥṭāhā ḥṣad ḥṭāhā', meaning: 'Кто сеет грех — пожнёт грех' },
      { original: 'ܠܐ ܡܨܝܐ ܚܕ ܒܪܢܫܐ ܠܡܗܘܐ ܬܡܝܡܐ', translation: 'lā mṣyā ḥad barnāšā lmhāwā tammā', meaning: 'Ни один человек не может быть совершенным' },
      { original: 'ܡܠܟܐ ܕܪܚܡ ܠܥܡܗ ܡܬܬܪܡ', translation: 'malkā d-raḥem l-ʿammeh mttarmā', meaning: 'Царь, любящий свой народ, будет возвышен' },
    ],
    reading: [],
  },

  // ============ АНГЛИЙСКИЙ ============
  {
    id: 'english',
    name: 'Английский',
    nativeName: 'English',
    tagline: 'Lingua franca современного мира',
    description: 'Германский язык, мировой язык общения',
    longDescription: 'Английский язык — западногерманский язык индоевропейской семьи. Возник в Англии в раннем Средневековье на основе англо-фризских диалектов. Сегодня это lingua franca международного общения, науки, бизнеса и интернета. На английском говорят более 1,5 миллиардов человек по всему миру, и для около 380 миллионов он является родным. Английский — официальный язык 67 государств и одна из рабочих языков ООН, ЕС, НАТО и многих других международных организаций.',
    family: 'Индоевропейская, германская ветвь',
    speakers: '~1,5 млрд',
    script: 'Латиница (26 букв)',
    direction: 'ltr',
    era: 'Современный',
    color: 'emerald',
    gradient: 'from-emerald-600 to-teal-600',
    accent: 'bg-emerald-600',
    emoji: '🇬🇧',
    history: [
      'V век — вторжение англов, саксов и ютов в Британию',
      'VII–XI века — староанглийский период (Beowulf)',
      '1066 год — нормандское завоевание, влияние французского',
      'XV–XVII века — великий сдвиг гласных, формирование современного английского',
      'XX век — глобальное распространение английского',
    ],
    alphabet: [
      { letter: 'A', name: 'ay', transcription: '/eɪ/', example: 'Apple', exampleTranslation: 'яблоко' },
      { letter: 'B', name: 'bee', transcription: '/biː/', example: 'Book', exampleTranslation: 'книга' },
      { letter: 'C', name: 'see', transcription: '/siː/', example: 'Cat', exampleTranslation: 'кот' },
      { letter: 'D', name: 'dee', transcription: '/diː/', example: 'Dog', exampleTranslation: 'собака' },
      { letter: 'E', name: 'ee', transcription: '/iː/', example: 'Egg', exampleTranslation: 'яйцо' },
      { letter: 'F', name: 'ef', transcription: '/ef/', example: 'Fish', exampleTranslation: 'рыба' },
      { letter: 'G', name: 'gee', transcription: '/dʒiː/', example: 'Goat', exampleTranslation: 'козёл' },
      { letter: 'H', name: 'aitch', transcription: '/eɪtʃ/', example: 'House', exampleTranslation: 'дом' },
      { letter: 'I', name: 'eye', transcription: '/aɪ/', example: 'Ice', exampleTranslation: 'лёд' },
      { letter: 'J', name: 'jay', transcription: '/dʒeɪ/', example: 'Juice', exampleTranslation: 'сок' },
      { letter: 'K', name: 'kay', transcription: '/keɪ/', example: 'Key', exampleTranslation: 'ключ' },
      { letter: 'L', name: 'el', transcription: '/el/', example: 'Lion', exampleTranslation: 'лев' },
      { letter: 'M', name: 'em', transcription: '/em/', example: 'Moon', exampleTranslation: 'луна' },
      { letter: 'N', name: 'en', transcription: '/en/', example: 'Nose', exampleTranslation: 'нос' },
      { letter: 'O', name: 'oh', transcription: '/oʊ/', example: 'Orange', exampleTranslation: 'апельсин' },
      { letter: 'P', name: 'pee', transcription: '/piː/', example: 'Pen', exampleTranslation: 'ручка' },
      { letter: 'Q', name: 'cue', transcription: '/kjuː/', example: 'Queen', exampleTranslation: 'королева' },
      { letter: 'R', name: 'ar', transcription: '/ɑːr/', example: 'Rain', exampleTranslation: 'дождь' },
      { letter: 'S', name: 'ess', transcription: '/es/', example: 'Sun', exampleTranslation: 'солнце' },
      { letter: 'T', name: 'tee', transcription: '/tiː/', example: 'Tree', exampleTranslation: 'дерево' },
      { letter: 'U', name: 'you', transcription: '/juː/', example: 'Umbrella', exampleTranslation: 'зонт' },
      { letter: 'V', name: 'vee', transcription: '/viː/', example: 'Van', exampleTranslation: 'фургон' },
      { letter: 'W', name: 'double-u', transcription: '/ˈdʌbəl.juː/', example: 'Water', exampleTranslation: 'вода' },
      { letter: 'X', name: 'ex', transcription: '/eks/', example: 'Box', exampleTranslation: 'коробка' },
      { letter: 'Y', name: 'why', transcription: '/waɪ/', example: 'Yellow', exampleTranslation: 'жёлтый' },
      { letter: 'Z', name: 'zee', transcription: '/ziː/', example: 'Zebra', exampleTranslation: 'зебра' },
    ],
    phrases: [
      { original: 'Hello!', transcription: 'həˈloʊ', translation: 'Привет!' },
      { original: 'How are you?', transcription: 'haʊ ɑːr juː', translation: 'Как дела?' },
      { original: 'Nice to meet you', transcription: 'naɪs tuː miːt juː', translation: 'Приятно познакомиться' },
      { original: 'Thank you very much', transcription: 'θæŋk juː ˈvɛri mʌtʃ', translation: 'Большое спасибо' },
      { original: 'You\'re welcome', transcription: 'jʊər ˈwɛlkəm', translation: 'Не за что' },
      { original: 'Excuse me', transcription: 'ɪkˈskjuːz miː', translation: 'Извините' },
      { original: 'I don\'t understand', transcription: 'aɪ doʊnt ʌndərˈstænd', translation: 'Я не понимаю' },
      { original: 'My name is...', transcription: 'maɪ neɪm ɪz', translation: 'Меня зовут...' },
      { original: 'Where is...?', transcription: 'wɛər ɪz', translation: 'Где...?' },
      { original: 'How much is it?', transcription: 'haʊ mʌtʃ ɪz ɪt', translation: 'Сколько это стоит?' },
      { original: 'See you later', transcription: 'siː juː ˈleɪtər', translation: 'Увидимся позже' },
      { original: 'I love you', transcription: 'aɪ lʌv juː', translation: 'Я тебя люблю' },
    ],
    lessons: [
      {
        id: 'en-1',
        title: 'Greetings and Introductions',
        level: 'Начальный',
        description: 'Базовые приветствия и представление',
        vocabulary: [
          { word: 'hello', transcription: 'həˈloʊ', translation: 'привет' },
          { word: 'goodbye', transcription: 'ˌɡʊdˈbaɪ', translation: 'до свидания' },
          { word: 'name', transcription: 'neɪm', translation: 'имя' },
          { word: 'friend', transcription: 'frɛnd', translation: 'друг' },
          { word: 'please', transcription: 'pliːz', translation: 'пожалуйста' },
        ],
        grammarNote: 'В английском нет формального/неформального «вы» — универсальное you. Порядок слов строгий SVO: Subject — Verb — Object. Для вопроса инверсия: Are you a student? Действуют времена: Present Simple, Present Continuous, Past Simple, Present Perfect, Future.',
      },
      {
        id: 'en-2',
        title: 'Numbers and Time',
        level: 'Начальный',
        description: 'Числа, время, дни недели',
        vocabulary: [
          { word: 'one', transcription: 'wʌn', translation: 'один' },
          { word: 'two', transcription: 'tuː', translation: 'два' },
          { word: 'three', transcription: 'θriː', translation: 'три' },
          { word: 'Monday', transcription: 'ˈmʌndeɪ', translation: 'понедельник' },
          { word: 'today', transcription: 'təˈdeɪ', translation: 'сегодня' },
          { word: 'tomorrow', transcription: 'təˈmɔːroʊ', translation: 'завтра' },
          { word: 'time', transcription: 'taɪm', translation: 'время' },
          { word: 'hour', transcription: 'ˈaʊər', translation: 'час' },
        ],
        grammarNote: 'Английские числа: 11-19 — исключения (eleven, twelve, thirteen...). Порядковые: first, second, third, fourth. Время: It\'s five o\'clock / half past three / quarter to four.',
      },
      {
        id: 'en-3',
        title: 'Travel and Directions',
        level: 'Средний',
        description: 'В аэропорту, в гостинице, на улице',
        vocabulary: [
          { word: 'airport', transcription: 'ˈɛərpɔːrt', translation: 'аэропорт' },
          { word: 'hotel', transcription: 'hoʊˈtɛl', translation: 'отель' },
          { word: 'ticket', transcription: 'ˈtɪkɪt', translation: 'билет' },
          { word: 'left', transcription: 'lɛft', translation: 'лево' },
          { word: 'right', transcription: 'raɪt', translation: 'право' },
          { word: 'straight', transcription: 'streɪt', translation: 'прямо' },
          { word: 'taxi', transcription: 'ˈtæksi', translation: 'такси' },
          { word: 'train', transcription: 'treɪn', translation: 'поезд' },
        ],
        grammarNote: 'Present Continuous для будущего: I\'m flying tomorrow. Модальные глаголы: can (мочь), could (мог бы), would like (хотел бы). Can you help me? — Можете помочь?',
      },
    ],
    quiz: [
      {
        question: 'How many letters are in the English alphabet?',
        options: ['24', '25', '26', '27'],
        correct: 2,
        explanation: 'The English alphabet has 26 letters, A through Z.',
      },
      {
        question: 'What does "Thank you" mean?',
        options: ['Привет', 'Спасибо', 'До свидания', 'Извините'],
        correct: 1,
        explanation: 'Thank you — благодарность, по-русски «спасибо».',
      },
      {
        question: 'Choose the correct sentence:',
        options: ['I goes to school', 'I go to school', 'I going to school', 'I am go to school'],
        correct: 1,
        explanation: 'В Present Simple с I используется базовая форма глагола: I go to school.',
      },
      {
        question: 'What is the past tense of "go"?',
        options: ['goed', 'gone', 'went', 'going'],
        correct: 2,
        explanation: 'Go — went — gone. Неправильный глагол.',
      },
      {
        question: 'Which is correct?',
        options: ['She don\'t like tea', 'She doesn\'t likes tea', 'She doesn\'t like tea', 'She not like tea'],
        correct: 2,
        explanation: 'She doesn\'t like tea. После doesn\'t глагол без -s.',
      },
    ],
    culture: [
      { emoji: '🌐', title: 'Глобальный язык', content: 'Английский — официальный язык 67 стран и lingua franca современного мира. На нём создано 60% контента интернета, он рабочий язык международной авиации, мореплавания и науки.' },
      { emoji: '📚', title: 'Шекспир изменил язык', content: 'Уильям Шекспир (1564–1616) ввёл в английский около 1700 новых слов: «assassination», «eyeball», «fashionable», «lonely», «manager». Без него английский был бы совсем другим.' },
      { emoji: '🔤', title: 'Огромный словарь', content: 'В Oxford English Dictionary более 600 000 слов — это один из самых больших словарей в мире. Ежегодно добавляется 4000 новых слов. Английский активно заимствует из всех языков мира.' },
      { emoji: '🎵', title: 'Язык поп-культуры', content: 'Английский — язык голливудского кино, британской музыки (Beatles, Adele, Ed Sheeran) и поп-культуры. Это делает его особенно привлекательным для изучения молодёжью по всему миру.' },
    ],
    proverbs: [
      { original: 'A picture is worth a thousand words', translation: 'Картина стоит тысячи слов', meaning: 'Лучше один раз увидеть' },
      { original: 'Actions speak louder than words', translation: 'Действия говорят громче слов', meaning: 'Судите по поступкам, не по словам' },
      { original: 'When in Rome, do as the Romans do', translation: 'В Риме делай как римляне', meaning: 'Принимай местные обычаи' },
      { original: 'The early bird catches the worm', translation: 'Ранняя птичка ловит червяка', meaning: 'Кто рано встаёт, тому Бог даёт' },
    ],
    reading: [],
  },

  // ============ ГРЕЧЕСКИЙ ============
  {
    id: 'greek',
    name: 'Греческий',
    nativeName: 'Ελληνικά',
    tagline: 'Язык Гомера, Платона и Аристотеля',
    description: 'Язык с 3400-летней документированной историей',
    longDescription: 'Греческий язык — индоевропейский язык, на котором говорят около 13 миллионов человек, в основном в Греции и на Кипре. Греческий имеет самую длинную задокументированную историю среди всех индоевропейских языков — более 3400 лет. На нём написаны «Илиада» и «Одиссея» Гомера, труды Платона и Аристотеля, Новый Завет. Греческий алфавит (24 буквы) — первый алфавит с обозначением гласных, оказавший влияние на латиницу и кириллицу. Современный греческий (димотика) — официальный язык Греции и Кипра.',
    family: 'Индоевропейская, греческая ветвь',
    speakers: '~13,5 млн',
    script: 'Греческий алфавит (24 буквы)',
    direction: 'ltr',
    era: 'Современный (с микенского периода)',
    color: 'cyan',
    gradient: 'from-cyan-600 to-blue-400',
    accent: 'bg-cyan-600',
    emoji: '🇬🇷',
    history: [
      'Около 1450 г. до н.э. — микенский греческий (линейное письмо Б)',
      'VIII век до н.э. — создание греческого алфавита на основе финикийского',
      'V–IV века до н.э. — классическая Аттика (Платон, Аристотель)',
      'I век н.э. — койне, язык Нового Завета',
      '1976 год — димотика объявлена официальным языком Греции',
    ],
    alphabet: [
      { letter: 'Α', name: 'Альфа', transcription: 'a', example: 'Αγάπη', exampleTranslation: 'agápi — любовь' },
      { letter: 'Β', name: 'Бета/Вита', transcription: 'v', example: 'Βιβλίο', exampleTranslation: 'vivlío — книга' },
      { letter: 'Γ', name: 'Гамма', transcription: 'gh/i', example: 'Γάτα', exampleTranslation: 'gáta — кошка' },
      { letter: 'Δ', name: 'Дельта', transcription: 'dh', example: 'Δέντρο', exampleTranslation: 'déndro — дерево' },
      { letter: 'Ε', name: 'Эпсилон', transcription: 'e', example: 'Έτος', exampleTranslation: 'étos — год' },
      { letter: 'Ζ', name: 'Дзета', transcription: 'z', example: 'Ζωή', exampleTranslation: 'zoí — жизнь' },
      { letter: 'Η', name: 'Ита', transcription: 'i', example: 'Ήλιος', exampleTranslation: 'ílios — солнце' },
      { letter: 'Θ', name: 'Тета', transcription: 'th', example: 'Θάλασσα', exampleTranslation: 'θálasa — море' },
      { letter: 'Ι', name: 'Йота', transcription: 'i', example: 'Ιστορία', exampleTranslation: 'istoría — история' },
      { letter: 'Κ', name: 'Каппа', transcription: 'k', example: 'Καφές', exampleTranslation: 'kafés — кофе' },
      { letter: 'Λ', name: 'Лямбда', transcription: 'l', example: 'Λόγος', exampleTranslation: 'lógos — слово' },
      { letter: 'Μ', name: 'Мю', transcription: 'm', example: 'Μητέρα', exampleTranslation: 'mitéra — мать' },
      { letter: 'Ν', name: 'Ню', transcription: 'n', example: 'Νερό', exampleTranslation: 'neró — вода' },
      { letter: 'Ξ', name: 'Кси', transcription: 'x/ks', example: 'Ξένος', exampleTranslation: 'xénos — чужак' },
      { letter: 'Ο', name: 'Омикрон', transcription: 'o', example: 'Όρος', exampleTranslation: 'óros — гора' },
      { letter: 'Π', name: 'Пи', transcription: 'p', example: 'Πατέρας', exampleTranslation: 'patéras — отец' },
      { letter: 'Ρ', name: 'Ро', transcription: 'r', example: 'Ρόδο', exampleTranslation: 'ródo — роза' },
      { letter: 'Σ', name: 'Сигма', transcription: 's', example: 'Σπίτι', exampleTranslation: 'spíti — дом' },
      { letter: 'Τ', name: 'Тау', transcription: 't', example: 'Τυρί', exampleTranslation: 'tirí — сыр' },
      { letter: 'Υ', name: 'Ипсилон', transcription: 'i', example: 'Υπέροχο', exampleTranslation: 'ypérocho — прекрасный' },
      { letter: 'Φ', name: 'Фи', transcription: 'f', example: 'Φως', exampleTranslation: 'fos — свет' },
      { letter: 'Χ', name: 'Хи', transcription: 'ch/h', example: 'Χρόνος', exampleTranslation: 'chrónos — время' },
      { letter: 'Ψ', name: 'Пси', transcription: 'ps', example: 'Ψυχή', exampleTranslation: 'psychí — душа' },
      { letter: 'Ω', name: 'Омега', transcription: 'o', example: 'Ωραίος', exampleTranslation: 'oraíos — красивый' },
    ],
    phrases: [
      { original: 'Γειά σας!', transcription: 'Yiá sas!', translation: 'Здравствуйте!' },
      { original: 'Καλημέρα!', transcription: 'Kaliméra!', translation: 'Доброе утро!' },
      { original: 'Καλησπέρα!', transcription: 'Kalispéra!', translation: 'Добрый вечер!' },
      { original: 'Ευχαριστώ', transcription: 'Efharistó', translation: 'Спасибо' },
      { original: 'Παρακαλώ', transcription: 'Parakaló', translation: 'Пожалуйста' },
      { original: 'Συγγνώμη', transcription: 'Sygnómi', translation: 'Извините' },
      { original: 'Δεν καταλαβαίνω', transcription: 'Den katalavéno', translation: 'Я не понимаю' },
      { original: 'Με λένε...', transcription: 'Me léne...', translation: 'Меня зовут...' },
      { original: 'Πόσο κάνει;', transcription: 'Póso káni?', translation: 'Сколько стоит?' },
      { original: 'Πού είναι...;', transcription: 'Poú íne...?', translation: 'Где находится...?' },
      { original: 'Ναι', transcription: 'Né', translation: 'Да' },
      { original: 'Όχι', transcription: 'Óchi', translation: 'Нет' },
    ],
    lessons: [
      {
        id: 'el-1',
        title: 'Основы новогреческого',
        level: 'Начальный',
        description: 'Димотика — современный греческий',
        vocabulary: [
          { word: 'γεια', transcription: 'yia', translation: 'привет' },
          { word: 'ευχαριστώ', transcription: 'efharistó', translation: 'спасибо' },
          { word: 'ναι', transcription: 'né', translation: 'да' },
          { word: 'όχι', transcription: 'óchi', translation: 'нет' },
          { word: 'νερό', transcription: 'neró', translation: 'вода' },
        ],
        grammarNote: 'В новогреческом 5 падежей (именительный, родительный, винительный, звательный, притяжательный). Определённый артикль: ο (м.р.), η (ж.р.), το (ср.р.). Глаголы спрягаются по лицам и числам в настоящем, прошедшем и будущем временах.',
      },
      {
        id: 'el-2',
        title: 'Семья и повседневная жизнь',
        level: 'Средний',
        description: 'Члены семьи и бытовые слова',
        vocabulary: [
          { word: 'πατέρας', transcription: 'patéras', translation: 'отец' },
          { word: 'μητέρα', transcription: 'mitéra', translation: 'мать' },
          { word: 'αδερφός', transcription: 'aderfós', translation: 'брат' },
          { word: 'αδερφή', transcription: 'aderení', translation: 'сестра' },
          { word: 'σπίτι', transcription: 'spíti', translation: 'дом' },
          { word: 'δουλειά', transcription: 'doulá', translation: 'работа' },
          { word: 'φαγητό', transcription: 'fagidó', translation: 'еда' },
          { word: 'καφές', transcription: 'kafés', translation: 'кофе' },
        ],
        grammarNote: 'Звательный падеж используется при обращении: Γιώργο! (Георгий!). Двойной артикль в притяжательной конструкции: ο φίλος μου (мой друг), literally «the friend the-my».',
      },
      {
        id: 'el-3',
        title: 'Древнегреческие корни',
        level: 'Продвинутый',
        description: 'Слова, вошедшие в мировой лексикон',
        vocabulary: [
          { word: 'δημοκρατία', transcription: 'dimokratía', translation: 'демократия' },
          { word: 'φιλοσοφία', transcription: 'filosofía', translation: 'философия' },
          { word: 'θεάτρο', transcription: 'théatro', translation: 'театр' },
          { word: 'ιστορία', transcription: 'istoría', translation: 'история' },
          { word: 'γεωγραφία', transcription: 'geografía', translation: 'география' },
          { word: 'άτομο', transcription: 'átomo', translation: 'атом /个人' },
          { word: 'πρόβλημα', transcription: 'próblima', translation: 'проблема' },
          { word: 'σύστημα', transcription: 'sístima', translation: 'система' },
        ],
        grammarNote: 'Греческие корни лежат в основе множества научных терминов: bio- (жизнь), geo- (земля), logos (слово), grapho (пишу). Знание этих корней облегчает изучение терминологии в науке.',
      },
    ],
    quiz: [
      {
        question: 'Сколько букв в греческом алфавите?',
        options: ['22', '24', '26', '28'],
        correct: 1,
        explanation: 'В греческом алфавите 24 буквы: от Альфа до Омега.',
      },
      {
        question: 'Что означает «Ευχαριστώ»?',
        options: ['Привет', 'Спасибо', 'Извините', 'До свидания'],
        correct: 1,
        explanation: 'Ευχαριστώ (efharistó) — спасибо.',
      },
      {
        question: 'Какая буква первая в греческом алфавите?',
        options: ['Β', 'Γ', 'Α', 'Ω'],
        correct: 2,
        explanation: 'Α (Альфа) — первая буква греческого алфавита.',
      },
      {
        question: 'На каком языке написан Новый Завет?',
        options: ['Латынь', 'Древнегреческий (койне)', 'Арамейский', 'Иврит'],
        correct: 1,
        explanation: 'Новый Завет написан на койне — общегреческом языке I века н.э.',
      },
      {
        question: 'Какая буква последняя в греческом алфавите?',
        options: ['Σ', 'Ψ', 'Ω', 'Χ'],
        correct: 2,
        explanation: 'Ω (Омега) — последняя буква греческого алфавита.',
      },
    ],
    culture: [
      { emoji: '🏛️', title: 'Колыбель демократии', content: 'Слово «демократия» (δημοκρατία) — греческое, от δῆμος (народ) + κράτος (власть). Афинская демократия V века до н.э. стала прообразом современных демократических институтов.' },
      { emoji: '🔬', title: 'Язык науки', content: 'Греческие корни лежат в основе научной терминологии: биология, физика, философия, математика, география, астрономия. Греческий алфавит используется в математике и физике (π, Σ, Δ, λ, α, β, γ).' },
      { emoji: '📜', title: 'Гомеровский эпос', content: '«Илиада» и «Одиссея» Гомера (VIII век до н.э.) — древнейшие памятники европейской литературы. Эти поэмы изучаются по сей день и оказали огромное влияние на мировую культуру.' },
      { emoji: '☦️', title: 'Язык Нового Завета', content: 'Новый Завет написан на койне — общегреческом языке I века н.э. Септуагинта — греческий перевод Ветхого Завета, сделанный в III веке до н.э. в Александрии.' },
    ],
    proverbs: [
      { original: 'Η γνώση είναι δύναμη', translation: 'I gnōsí éinai dýnami', meaning: 'Знание — сила' },
      { original: 'Αργά αλλά σταθερά', translation: 'Argá allá statherá', meaning: 'Медленно, но верно' },
      { original: 'Κάθε αρχή και δύσκολη', translation: 'Káthe archí kai dýskoli', meaning: 'Любое начало трудно' },
      { original: 'Όποιος σκάβει το λάκκο του άλλου, πέφτει μέσα', translation: 'Ópios skávei to lákko tou állou, péfti mésa', meaning: 'Копаешь яму другому — сам в неё попадёшь' },
    ],
    reading: [],
  },

  // ============ СТАРОСЛАВЯНСКИЙ ============
  {
    id: 'slavic',
    name: 'Славянский',
    nativeName: 'Словѣньскъ',
    tagline: 'Древний язык Кирилла и Мефодия',
    description: 'Старославянский — первый литературный язык славян',
    longDescription: 'Старославянский язык — первый литературный язык славян, созданный в IX веке византийскими миссионерами Кириллом и Мефодием для перевода богослужебных текстов. Основой послужил южномакедонский (солунский) диалект древнеболгарского языка. Старославянский не был разговорным языком какого-либо народа — это искусственно нормированный книжный язык. На нём написаны древнейшие памятники славянской письменности: Евангелия, Псалтыри, жития святых. Язык использует кириллицу (или глаголицу) и содержит звуки, отсутствующие в современных славянских языках (носы, ѣ, ъ, ь).',
    family: 'Индоевропейская, славянская ветвь',
    speakers: 'Язык богослужения и науки',
    script: 'Кириллица / Глаголица',
    direction: 'ltr',
    era: 'IX–XI века',
    color: 'purple',
    gradient: 'from-purple-700 to-pink-600',
    accent: 'bg-purple-700',
    emoji: '📖',
    history: [
      '862 год — византийский император отправляет Кирилла и Мефодия в Великую Моравию',
      '863 год — создание славянской азбуки (глаголицы)',
      '885 год — изгнание учеников Мефодия из Великой Моравии, распространение в Болгарии',
      'IX–XI века — золотой век старославянской письменности',
      'XI век — появление церковнославянского языка как редакции старославянского',
    ],
    alphabet: [
      { letter: 'А', name: 'азъ', transcription: 'a', example: 'Агнецъ', exampleTranslation: 'agnьcъ — агнец' },
      { letter: 'Б', name: 'боукы', transcription: 'b', example: 'Богъ', exampleTranslation: 'bogъ — Бог' },
      { letter: 'В', name: 'вѣдѣ', transcription: 'v', example: 'Вѣра', exampleTranslation: 'věra — вера' },
      { letter: 'Г', name: 'глаголи', transcription: 'g', example: 'Гласъ', exampleTranslation: 'glasъ — голос' },
      { letter: 'Д', name: 'добро', transcription: 'd', example: 'Домъ', exampleTranslation: 'domъ — дом' },
      { letter: 'Е', name: 'єсть', transcription: 'e', example: 'Единъ', exampleTranslation: 'edinъ — один' },
      { letter: 'Ж', name: 'живѣте', transcription: 'zh', example: 'Животъ', exampleTranslation: 'zhivotъ — жизнь' },
      { letter: 'Ѕ', name: 'ѕѣло', transcription: 'dz', example: 'Ѕвѣзда', exampleTranslation: 'dzvězda — звезда' },
      { letter: 'З', name: 'землꙗ', transcription: 'z', example: 'Землꙗ', exampleTranslation: 'zemlja — земля' },
      { letter: 'И', name: 'иже', transcription: 'i', example: 'Истоучитель', exampleTranslation: 'istoučitelь — наставник' },
      { letter: 'І', name: 'и десетеричное', transcription: 'i', example: 'Іисусъ', exampleTranslation: 'Iisusъ — Иисус' },
      { letter: 'К', name: 'како', transcription: 'k', example: 'Книга', exampleTranslation: 'kniga — книга' },
      { letter: 'Л', name: 'людиѥ', transcription: 'l', example: 'Людиѥ', exampleTranslation: 'ljudije — люди' },
      { letter: 'М', name: 'мꙑслите', transcription: 'm', example: 'Миръ', exampleTranslation: 'mirъ — мир' },
      { letter: 'Н', name: 'нашь', transcription: 'n', example: 'Нощь', exampleTranslation: 'noštь — ночь' },
      { letter: 'О', name: 'онъ', transcription: 'o', example: 'Око', exampleTranslation: 'oko — глаз' },
      { letter: 'П', name: 'покои', transcription: 'p', example: 'Поть', exampleTranslation: 'potь — путь' },
      { letter: 'Р', name: 'рьци', transcription: 'r', example: 'Река', exampleTranslation: 'reka — река' },
      { letter: 'С', name: 'слово', transcription: 's', example: 'Слово', exampleTranslation: 'slovo — слово' },
      { letter: 'Т', name: 'тврьдо', transcription: 't', example: 'Тьло', exampleTranslation: 'tьlo — тело' },
      { letter: 'У', name: 'оукъ', transcription: 'u', example: 'Оучитель', exampleTranslation: 'oučitelь — учитель' },
      { letter: 'Ф', name: 'фрьта', transcription: 'f', example: 'Фарисеи', exampleTranslation: 'farisei — фарисеи' },
      { letter: 'Х', name: 'хѣръ', transcription: 'kh', example: 'Храмъ', exampleTranslation: 'khramъ — храм' },
      { letter: 'Ѡ', name: 'омега', transcription: 'o', example: 'Ѡтрокъ', exampleTranslation: 'otrokъ — отрок' },
      { letter: 'Ц', name: 'ци', transcription: 'ts', example: 'Црькꙑ', exampleTranslation: 'crьky — церкви' },
      { letter: 'Ч', name: 'чрьвь', transcription: 'ch', example: 'Чловѣкъ', exampleTranslation: 'člověkъ — человек' },
      { letter: 'Ш', name: 'ша', transcription: 'sh', example: 'Широка', exampleTranslation: 'shiroka — широка' },
      { letter: 'Щ', name: 'шта', transcription: 'sht', example: 'Щедроты', exampleTranslation: 'shtedroty — щедроты' },
      { letter: 'Ъ', name: 'єръ', transcription: 'ъ (сверхкраткий)', example: 'Сънъ', exampleTranslation: 'sъnъ — сон' },
      { letter: 'Ы', name: 'єры', transcription: 'y', example: 'Сынъ', exampleTranslation: 'synъ — сын' },
      { letter: 'Ь', name: 'єрь', transcription: 'ь (сверхкраткий)', example: 'Конь', exampleTranslation: 'konь — конь' },
      { letter: 'Ѣ', name: 'ѣть (ять)', transcription: 'ya/e', example: 'Вѣра', exampleTranslation: 'věra — вера' },
      { letter: 'Ю', name: 'ю', transcription: 'yu', example: 'Юность', exampleTranslation: 'yunostь — юность' },
      { letter: 'Ꙗ', name: 'ѣ (я)', transcription: 'ya', example: 'Ꙗзыкъ', exampleTranslation: 'jazykъ — язык' },
      { letter: 'Ѧ', name: 'юсъ малый', transcription: 'ę', example: 'Ѧдь', exampleTranslation: 'ędь — еда (носовой)' },
      { letter: 'Ѫ', name: 'юсъ большой', transcription: 'ǫ', example: 'Ѫзыкъ', exampleTranslation: 'ǫzykъ — язык (носовой)' },
      { letter: 'Ѩ', name: 'юсъ малый йотированный', transcription: 'yen', example: 'Ѩгкъ', exampleTranslation: 'jenžkъ — узкий' },
      { letter: 'Ѭ', name: 'юсъ большой йотированный', transcription: 'yon', example: 'Ѭнъкъ', exampleTranslation: 'jonъkъ — ёмкий' },
    ],
    phrases: [
      { original: 'Миръ тебѣ!', transcription: 'Mirъ tebě!', translation: 'Мир тебе!' },
      { original: 'Господи помилуй', transcription: 'Gospodi pomilui', translation: 'Господи помилуй' },
      { original: 'Слава Отцу и Сыну и Святому Духу', transcription: 'Slava Otcu i Synu i Svetomu Duxu', translation: 'Слава Отцу и Сыну и Святому Духу' },
      { original: 'Аминь', transcription: 'Aminь', translation: 'Аминь' },
      { original: 'Аллилуиа', transcription: 'Aliluiia', translation: 'Аллилуйя' },
      { original: 'Въ началѣ бѣ Слово', transcription: 'Vъ načalě bě Slovo', translation: 'В начале было Слово' },
      { original: 'Отче нашъ', transcription: 'Otče našь', translation: 'Отче наш' },
      { original: 'Иже херувимы', transcription: 'Iže xeruvimy', translation: 'Иже херувимы (тайная вечеря)' },
      { original: 'Святъ, святъ, святъ', transcription: 'Svetъ, svetъ, svetъ', translation: 'Свят, свят, свят' },
      { original: 'Богъ съ нами', transcription: 'Bogъ sъ nami', translation: 'Бог с нами' },
    ],
    lessons: [
      {
        id: 'sla-1',
        title: 'Старославянская азбука',
        level: 'Начальный',
        description: 'Кириллица и названия букв',
        vocabulary: [
          { word: 'азъ', transcription: 'azъ', translation: 'я (буква А)' },
          { word: 'боукы', transcription: 'buky', translation: 'буква (буква Б)' },
          { word: 'вѣдѣ', transcription: 'vědě', translation: 'ведать (буква В)' },
          { word: 'глаголи', transcription: 'glagoli', translation: 'говори (буква Г)' },
          { word: 'добро', transcription: 'dobro', translation: 'добро (буква Д)' },
        ],
        grammarNote: 'Названия букв старославянской кириллицы имеют смысл: Аз (я), Буки (буквы), Веди (знаю) — «Я буквы знаю». Эта акростиховая традиция заимствована из греческого алфавита.',
      },
      {
        id: 'sla-2',
        title: 'Носовые гласные и ѣ',
        level: 'Средний',
        description: 'Особые звуки старославянского',
        vocabulary: [
          { word: 'рѫка', transcription: 'rǫka', translation: 'рука (носовой)' },
          { word: 'пѧть', transcription: 'pętь', translation: 'пять (носовой)' },
          { word: 'вѣра', transcription: 'věra', translation: 'вера (через ять)' },
          { word: 'мѣсто', transcription: 'město', translation: 'место (через ять)' },
          { word: 'сънъ', transcription: 'sъnъ', translation: 'сон (с ъ)' },
          { word: 'дьнь', transcription: 'dьnь', translation: 'день (с ь)' },
        ],
        grammarNote: 'Старославянский имел носовые гласные ѧ (ę) и ѫ (ǫ), которые в современных славянских языках утратили носовой характер. Ѫ (юс большой) сохранился в польском как ę. Ѣ (ять) — особый гласный, в разных славянских языках перешёл в «е» или «я».',
      },
      {
        id: 'sla-3',
        title: 'Богослужебные тексты',
        level: 'Продвинутый',
        description: 'Литургические формулы',
        vocabulary: [
          { word: 'Господи', transcription: 'Gospodi', translation: 'Господи (звательный падеж)' },
          { word: 'Отче', transcription: 'Otče', translation: 'Отче (звательный падеж)' },
          { word: 'Царю', transcription: 'Carju', translation: 'Царю (звательный падеж)' },
          { word: 'помилуи', transcription: 'pomilui', translation: 'помилуй' },
          { word: 'спаси', transcription: 'spasi', translation: 'спаси' },
          { word: 'съхрані', transcription: 'sъxchrani', translation: 'сохрани' },
        ],
        grammarNote: 'Старославянский имеет звательный падеж (вокатив) для обращений: Господь → Господи, отецъ → отче, цѣсарь → цѣсарю. В современных славянских языках вокатив сохранился в украинском, белорусском, сербском, хорватском, польском.',
      },
    ],
    quiz: [
      {
        question: 'Кто создал славянскую письменность?',
        options: ['Кирилл и Мефодий', 'Сергий Радонежский', 'Ярослав Мудрый', 'Иван Грозный'],
        correct: 0,
        explanation: 'Кирилл (Константин) и Мефодий в IX веке создали славянскую азбуку.',
      },
      {
        question: 'В каком веке возник старославянский язык?',
        options: ['V', 'VII', 'IX', 'XI'],
        correct: 2,
        explanation: 'Старославянский возник в IX веке (863 год — миссия в Моравию).',
      },
      {
        question: 'Что означает буква Ѣ (ять)?',
        options: ['Особый гласный звук', 'Носовой гласный', 'Твёрдый знак', 'Мягкий знак'],
        correct: 0,
        explanation: 'Ѣ (ять) — особый гласный звук, не совпадающий ни с е, ни с я.',
      },
      {
        question: 'Какая буква называется «азъ»?',
        options: ['Б', 'А', 'В', 'Г'],
        correct: 1,
        explanation: 'Азъ — название буквы А в старославянской кириллице.',
      },
      {
        question: 'Что такое носовые гласные в старославянском?',
        options: ['Ѹ, ѡ', 'Ѧ, Ѫ', 'Ѥ, Ѩ', 'Њ, Љ'],
        correct: 1,
        explanation: 'Ѧ (юс малый) и Ѫ (юс большой) — носовые гласные, обозначали [ę] и [ǫ].',
      },
    ],
    culture: [
      { emoji: '✝️', title: 'Язык христианизации', content: 'Старославянский стал языком христианизации всех славянских народов: болгар (864), сербов (867), русских (988), поляков (966). На нём писались первые переводы Библии и богослужебных книг.' },
      { emoji: '📖', title: 'Кириллица — мать славянских азбук', content: 'Из старославянской кириллицы произошли современная русская, украинская, белорусская, болгарская, сербская, македонская азбуки. Глаголица же вышла из употребления к XII веку.' },
      { emoji: '☦️', title: 'Кирилл и Мефодий', content: 'Братья Кирилл (827–869) и Мефодий (815–885) из Солуни создали славянскую письменность по просьбе византийского императора. Католическая церковь признала их святыми — «равноапостольными».' },
      { emoji: '📜', title: 'Древнейшие памятники', content: 'Самые древние старославянские рукописи: Саввина книга, Супрасльская рукопись, Енинский апостол (X–XI века). Они хранятся в библиотеках России, Болгарии, Сербии.' },
    ],
    proverbs: [
      { original: 'Слово въ устѣхъ съхранѧтъ', translation: 'Slovo vъ ustěxъ sъxranętь', meaning: 'Слово хранят в устах (о мудрости)' },
      { original: 'Книжнааго почитаниѥ — съкровище неиждиваемо', translation: 'Knižnaago počitanije — sъkrovišče neiždivaemo', meaning: 'Чтение книг — неисчерпаемое сокровище' },
      { original: 'Доброу мужю не лѣно бѣ', translation: 'Dobru mužu ne lěno bě', meaning: 'Доброму мужу не было лени' },
      { original: 'Вѧра безъ дѣлъ мрьтва естъ', translation: 'Věra bezъ dělъ mrьtva estъ', meaning: 'Вера без дел мертва есть' },
    ],
    reading: [],
  },

  // ============ ЦЕРКОВНОСЛАВЯНСКИЙ ============
  {
    id: 'church-slavonic',
    name: 'Церковный',
    nativeName: 'Церковнославѧнскїй',
    tagline: 'Язык православного богослужения',
    description: 'Церковнославянский язык русской редакции',
    longDescription: 'Церковнославянский язык — богослужебный язык Русской православной церкви и других славянских православных церквей. Возник как русская редакция старославянского языка после принятия христианства на Руси в 988 году. На протяжении 1000 лет служит языком богослужения, духовной литературы и иконописи. Использует кириллицу в её церковной (полууставной) форме с надстрочными знаками: ударениями (силами) и придыханиями. Церковнославянский — живой литургический язык, на нём совершаются все православные службы, читаются Евангелие и Псалтирь, поются гимны.',
    family: 'Индоевропейская, славянская ветвь',
    speakers: 'Богослужебный язык РПЦ и славянских церквей',
    script: 'Кириллица (полуустав) с надстрочными',
    direction: 'ltr',
    era: 'С XI века по настоящее время',
    color: 'stone',
    gradient: 'from-stone-700 to-amber-900',
    accent: 'bg-stone-700',
    emoji: '☦️',
    history: [
      '988 год — крещение Руси, появление славянского богослужения',
      'XI–XIV века — древнерусская редакция старославянского',
      'XV–XVII века — формирование собственно церковнославянского (среднеболгарская редакция)',
      '1650-е годы — никоновские реформы, унификация богослужебных книг',
      '1708 год — реформа гражданского шрифта Петра I, разделение светского и церковного письма',
    ],
    alphabet: [
      { letter: 'А', name: 'а', transcription: 'a', example: 'Аминь', exampleTranslation: 'Aminь — аминь' },
      { letter: 'Б', name: 'б', transcription: 'b', example: 'Богъ', exampleTranslation: 'Bogъ — Бог' },
      { letter: 'В', name: 'в', transcription: 'v', example: 'Вѣра', exampleTranslation: 'Věra — вера' },
      { letter: 'Г', name: 'г', transcription: 'g', example: 'Господь', exampleTranslation: 'Gospodь — Господь' },
      { letter: 'Д', name: 'д', transcription: 'd', example: 'Духъ', exampleTranslation: 'Duxъ — Дух' },
      { letter: 'Е', name: 'е', transcription: 'e', example: 'Евангелїе', exampleTranslation: 'Evangelie — Евангелие' },
      { letter: 'Ж', name: 'ж', transcription: 'zh', example: 'Животъ', exampleTranslation: 'Zhivotъ — жизнь' },
      { letter: 'Ѕ', name: 'ѕ', transcription: 'dz', example: 'Ѕвѣзда', exampleTranslation: 'Dzvězda — звезда' },
      { letter: 'З', name: 'з', transcription: 'z', example: 'Землѧ', exampleTranslation: 'Zemlja — земля' },
      { letter: 'И', name: 'и', transcription: 'i', example: 'Иисусъ', exampleTranslation: 'Iisusъ — Иисус' },
      { letter: 'І', name: 'і', transcription: 'i', example: 'Іерусалимъ', exampleTranslation: 'Ierusalimъ — Иерусалим' },
      { letter: 'К', name: 'к', transcription: 'k', example: 'Крестъ', exampleTranslation: 'Krestъ — крест' },
      { letter: 'Л', name: 'л', transcription: 'l', example: 'Литургїѧ', exampleTranslation: 'Liturgija — литургия' },
      { letter: 'М', name: 'м', transcription: 'm', example: 'Миръ', exampleTranslation: 'Mirъ — мир' },
      { letter: 'Н', name: 'н', transcription: 'n', example: 'Небо', exampleTranslation: 'Nebo — небо' },
      { letter: 'О', name: 'о', transcription: 'o', example: 'Отче', exampleTranslation: 'Otče — Отче' },
      { letter: 'П', name: 'п', transcription: 'p', example: 'Помилуи', exampleTranslation: 'Pomilui — помилуй' },
      { letter: 'Р', name: 'р', transcription: 'r', example: 'Рабъ', exampleTranslation: 'Rabъ — раб' },
      { letter: 'С', name: 'с', transcription: 's', example: 'Свѧтый', exampleTranslation: 'Svjatyj — святой' },
      { letter: 'Т', name: 'т', transcription: 't', example: 'Троица', exampleTranslation: 'Troica — Троица' },
      { letter: 'У', name: 'у', transcription: 'u', example: 'Учитель', exampleTranslation: 'Učitelь — учитель' },
      { letter: 'Ф', name: 'ф', transcription: 'f', example: 'Фарисеи', exampleTranslation: 'Farisei — фарисеи' },
      { letter: 'Х', name: 'х', transcription: 'kh', example: 'Храмъ', exampleTranslation: 'Khramъ — храм' },
      { letter: 'Ѡ', name: 'ѡ (омега)', transcription: 'o', example: 'Ѡтечествѡ', exampleTranslation: 'Otečestvo — отечество' },
      { letter: 'Ц', name: 'ц', transcription: 'ts', example: 'Царь', exampleTranslation: 'Carь — царь' },
      { letter: 'Ч', name: 'ч', transcription: 'ch', example: 'Человѣкъ', exampleTranslation: 'Čelověkъ — человек' },
      { letter: 'Ш', name: 'ш', transcription: 'sh', example: 'Шестокрилъ', exampleTranslation: 'Shestokrilъ — шестикрылый' },
      { letter: 'Щ', name: 'щ', transcription: 'sht', example: 'Щедроты', exampleTranslation: 'Shtedroty — щедроты' },
      { letter: 'Ъ', name: 'єръ', transcription: 'ъ', example: 'Сынъ', exampleTranslation: 'Synъ — сын' },
      { letter: 'Ы', name: 'єры', transcription: 'y', example: 'Бытїе', exampleTranslation: 'Bytie — бытие' },
      { letter: 'Ь', name: 'єрь', transcription: 'ь', example: 'Конь', exampleTranslation: 'Konь — конь' },
      { letter: 'Ѣ', name: 'ѧть (ятъ)', transcription: 'ya/e', example: 'Млѣко', exampleTranslation: 'Mlěko — молоко' },
      { letter: 'Ѩ', name: 'ѧ (юсъ)', transcription: 'ya', example: 'Свѧтый', exampleTranslation: 'Svjatyj — святой' },
      { letter: 'Ю', name: 'ю', transcription: 'yu', example: 'Юже', exampleTranslation: 'Juže — уже' },
      { letter: 'Ꙗ', name: 'ꙗ (ѥѻ)', transcription: 'ya', example: 'ꙗзыкъ', exampleTranslation: 'Jazykъ — язык' },
      { letter: 'Ѵ', name: 'ѵжица', transcription: 'i', example: 'Іѵанъ', exampleTranslation: 'Ivanъ — Иван' },
      { letter: 'Ѥ', name: 'ѥ (ѥсъ)', transcription: 'ye', example: 'Ѥже', exampleTranslation: 'Ježe — еже' },
    ],
    phrases: [
      { original: 'Господи помилуи', transcription: 'Gospodi pomilui', translation: 'Господи помилуй' },
      { original: 'Господи помилуи, Господи помилуи, Господи помилуи', transcription: '—', translation: 'Троекратное «Господи помилуй»' },
      { original: 'Слава Отцу и Сыну и Святому Духу', transcription: '—', translation: 'Слава Отцу и Сыну и Святому Духу' },
      { original: 'И нынѣ и присно и во вѣки вѣкомъ. Аминь.', transcription: '—', translation: 'И ныне и присно и во веки веков. Аминь.' },
      { original: 'Миръ всѣмъ', transcription: 'Mirъ vsěmъ', translation: 'Мир всем' },
      { original: 'И духови твоему', transcription: 'I duxovi tvoemu', translation: 'И духу твоему' },
      { original: 'Премудрость. Прости.', transcription: 'Premudrostь. Prosti.', translation: 'Премудрость. Внимаем.' },
      { original: 'Вонмемъ', transcription: 'Vonnemъ', translation: 'Будем внимательны' },
      { original: 'Аллилуїа, аллилуїа, аллилуїа', transcription: 'Alliluia', translation: 'Аллилуйя (3 раза)' },
      { original: 'Свѧтъ Бо́гъ, свѧтъ Крѣпкїй, свѧтъ Безсмертный', transcription: '—', translation: 'Святый Боже, Святый Крепкий, Святый Безсмертный' },
    ],
    lessons: [
      {
        id: 'cs-1',
        title: 'Богослужебные возгласы',
        level: 'Начальный',
        description: 'Возгласы священника на литургии',
        vocabulary: [
          { word: 'Благословенно царство', transcription: 'blagoslovenno carstvo', translation: 'Благословенно царство' },
          { word: 'Миръ всѣмъ', transcription: 'mirъ vsěmъ', translation: 'мир всем' },
          { word: 'Премудрость', transcription: 'premudrostь', translation: 'премудрость' },
          { word: 'Вонмемъ', transcription: 'vonnemъ', translation: 'будем внимать' },
          { word: 'Аминь', transcription: 'aminь', translation: 'аминь (истинно)' },
        ],
        grammarNote: 'Церковнославянские возгласы имеют фиксированную форму. «Аминь» — еврейское слово, означающее «истинно, да будет так». «Аллилуия» — «хвалите Бога». Эти формулы неизменны в богослужении.',
      },
      {
        id: 'cs-2',
        title: 'Надстрочные знаки',
        level: 'Средний',
        description: 'Ударения и придыхания',
        vocabulary: [
          { word: 'Бо́гъ', transcription: 'Bogъ', translation: 'Бог (с острым ударением)' },
          { word: 'Го́споди', transcription: 'Gospodi', translation: 'Господи (с ударением)' },
          { word: 'дх҃ъ', transcription: 'duxъ', translation: 'Духъ (с титлой — сокращением)' },
          { word: 'бг҃ъ', transcription: 'bogъ', translation: 'Богъ (с титлой)' },
          { word: 'і҆съ', transcription: 'Iisusъ', translation: 'Іисусъ (с титлой)' },
        ],
        grammarNote: 'Церковнославянские тексты используют надстрочные знаки: ударение (вария, оксия, камора), придыхание (исо), а также титлы для сокращения священных имён (Бг҃ъ = Богъ, Ісъ = Іисусъ, Хсъ = Христосъ).',
      },
      {
        id: 'cs-3',
        title: 'Молитва «Отче наш»',
        level: 'Продвинутый',
        description: 'Главная христианская молитва',
        vocabulary: [
          { word: 'Отче нашъ', transcription: 'Otče našь', translation: 'Отче наш' },
          { word: 'Иже еси на небесѣхъ', transcription: 'Iže esi na nebeseхъ', translation: 'сущий на небесах' },
          { word: 'да свѧтитсѧ имѧ Твое', transcription: 'da svjatitsja imja tvoe', translation: 'да святится имя Твоё' },
          { word: 'да прїидетъ царствїе Твое', transcription: 'da priidetъ carstvie tvoe', translation: 'да приидет царствие Твоё' },
          { word: 'да будетъ волѧ Твоѧ', transcription: 'da budetъ volja tvoja', translation: 'да будет воля Твоя' },
          { word: 'ѧкоже на небеси и на земли', transcription: 'jakоže na nebesi i na zemli', translation: 'как на небе, так и на земле' },
          { word: 'хлѣбъ нашъ насущный', transcription: 'xlěbъ našъ nasuščnyj', translation: 'хлеб наш насущный' },
          { word: 'даждь намъ днесь', transcription: 'dadь namъ dnesь', translation: 'дай нам сегодня' },
        ],
        grammarNote: 'Молитва «Отче наш» сохраняет архаичный синтаксис старославянского: звательный падеж (Отче), двойственное число в оригинале, формы аориста и имперфекта. Текст неизменен с IX века.',
      },
    ],
    quiz: [
      {
        question: 'Какова главная функция церковнославянского языка?',
        options: ['Разговорный', 'Богослужебный', 'Научный', 'Деловой'],
        correct: 1,
        explanation: 'Церковнославянский — язык православного богослужения, не разговорный.',
      },
      {
        question: 'Что такое «титла» в церковнославянском?',
        options: ['Ударение', 'Придыхание', 'Надстрочный знак сокращения', 'Знак препинания'],
        correct: 2,
        explanation: 'Титла — надстрочный знак, обозначающий сокращение священных имён: Бг҃ъ, Ісъ.',
      },
      {
        question: 'В каком году на Руси появилось славянское богослужение?',
        options: ['862', '988', '1054', '1453'],
        correct: 1,
        explanation: 'В 988 году при Владимире Великом Русь приняла христианство и славянское богослужение.',
      },
      {
        question: 'Что означает возглас «Аминь»?',
        options: ['Хвалите Бога', 'Истинно, да будет так', 'Господи помилуй', 'Мир всем'],
        correct: 1,
        explanation: 'Аминь (из иврита) — «истинно, да будет так», подтверждение молитвы.',
      },
      {
        question: 'Какая буква в церковнославянском обозначает «ять»?',
        options: ['ѧ', 'ѣ', 'ѡ', 'ѵ'],
        correct: 1,
        explanation: 'Ѣ (ять) — особый гласный, сохранившийся только в церковнославянском.',
      },
    ],
    culture: [
      { emoji: '⛪', title: 'Язык православного богослужения', content: 'Церковнославянский используется во всех православных славянских церквях: Русской, Сербской, Болгарской, Польской, Чешской. На нём совершаются литургии, читается Евангелие, поются гимны.' },
      { emoji: '🎨', title: 'Иконописные надписи', content: 'На православных иконах надписи делаются церковнославянским языком. Сокращённые имена (IC XC = Іисусъ Христосъ, MP ΘY = Мати Божїѧ) — это древняя традиция священных монограмм.' },
      { emoji: '🕯️', title: 'Литургия Иоанна Златоуста', content: 'Главная литургия Русской православной церкви составлена св. Иоанном Златоустом (IV век). Текст на церковнославянском практически не изменился с XI века — это живой голос тысячелетней традиции.' },
      { emoji: '📖', title: 'Остромирово Евангелие', content: 'Остромирово Евангелие (1056–1057) — древнейшая датированная рукопись Руси. Написано диаконом Григорием для новгородского посадника Остромира. Хранится в РНБ Санкт-Петербурга.' },
    ],
    proverbs: [
      { original: 'Богъ не въ силѣ, а въ правдѣ', translation: 'Bogъ ne vъ silě, a vъ pravdě', meaning: 'Бог не в силе, а в правде (Александр Невский)' },
      { original: 'Съ Богомъ въ путь', translation: 'Sъ Bogomъ vъ putь', meaning: 'С Богом в путь (благословение)' },
      { original: 'Время сѧ къ Божїю познанїю приближаетъ', translation: 'Vremja sja kъ Božiju poznaniju približaetъ', meaning: 'Время к Богопознанию приближает' },
      { original: 'Душа съ Божїею волею съгласна', translation: 'Duša sъ Božijeju voleju sъglasna', meaning: 'Душа с Божьей волей согласна' },
    ],
    reading: [],
  },
]

export function getLanguageById(id: string): Language | undefined {
  return languages.find((lang) => lang.id === id)
}
